version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - rag-network
    restart: always

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma
    networks:
      - rag-network
    restart: always

  api-rag:
    build: ./api-rag
    container_name: api-rag
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - CHROMA_DB=http://chromadb:8000
    depends_on:
      - ollama
      - chromadb
    networks:
      - rag-network
    restart: always

  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "5050:5050"
    depends_on:
      - api-rag
    networks:
      - rag-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NODE_ENV=development
    depends_on:
      - proxy
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  ollama-data:
  chroma-data:

networks:
  rag-network:
    driver: bridge
